'use strict';

/**
 * Smilepayz India payout paymentMethod codes (from Smilepayz ops).
 * Map IFSC bank code (first 4 letters) → Smilepayz Method string.
 */
const SMILEPAYZ_PAYMENT_METHODS = new Set([
  'ABHYUDAYA',
  'ABN',
  'ABU',
  'AHMEDABAD',
  'ALLAHABAD',
  'AXIS',
  'ANDHRA',
  'BOA',
  'BOB',
  'BOBAK',
  'BOI',
  'BONS',
  'BOR',
  'BOM',
  'BCB',
  'MUMBAI',
  'CANARA',
  'CBOI',
  'CITIBANK_IND',
  'CUB',
  'CITIZENCREDIT',
  'CORPORATION',
  'COSMOS',
  'DBS_IND',
  'DENA',
  'DHANALAKSHMI',
  'FEDERAL',
  'DICGC',
  'GBB',
  'HDFC',
  'HSBC_IND',
  'ICICI',
  'IDBI',
  'IOB',
  'IVB',
  'JAKB',
  'JSB',
  'KCB',
  'KJSB',
  'KARNATAKA',
  'JCB',
  'KSAB',
  'KVN',
  'KMB',
  'LVB',
  'MAHANAGAR',
  'MSB',
  'MASHREQBANK',
  'MUB',
  'MIZUHO_IND',
  'NAINITAL',
  'NIB',
  'NKGSB',
  'NNSB',
  'OIBS',
  'OBOC',
  'PJSB',
  'PAMB',
  'PASB',
  'PNB',
  'RATNAKAR',
  'RBOI',
  'SARASWAT',
  'SVB',
  'RBOS',
  'SHINHAN_IND',
  'SG',
  'SCB',
  'SBOBAJ',
  'SBOH',
  'SIB',
  'SBOM',
  'SBOMYSORE',
  'SBOP',
  'SBOT',
  'SPB',
  'SYNDICATE',
  'TMB',
  'TJSB',
  'UCO',
  'UNIOBOI',
  'UNITEDBOI',
  'VIJAYA',
  'YES',
  'TSAB',
  'OTHERS',
]);

/** IFSC bank code (chars 1–4) → Smilepayz paymentMethod */
const IFSC_PREFIX_TO_METHOD = {
  ABHY: 'ABHYUDAYA',
  ABNA: 'ABN',
  ADCB: 'ABU',
  AMCB: 'AHMEDABAD',
  ALLA: 'ALLAHABAD',
  UTIB: 'AXIS',
  ANDB: 'ANDHRA',
  BOFA: 'BOA',
  BARB: 'BOB',
  BBKM: 'BOBAK',
  BKID: 'BOI',
  NOSC: 'BONS',
  BJRA: 'BOR',
  RJTB: 'BOR',
  MAHB: 'BOM',
  BACB: 'BCB',
  BCBM: 'MUMBAI',
  CNRB: 'CANARA',
  CBIN: 'CBOI',
  CITI: 'CITIBANK_IND',
  CIUB: 'CUB',
  CCBL: 'CITIZENCREDIT',
  CORP: 'CORPORATION',
  COSB: 'COSMOS',
  DBSS: 'DBS_IND',
  BKDN: 'DENA',
  DLXB: 'DHANALAKSHMI',
  FDRL: 'FEDERAL',
  DICG: 'DICGC',
  GBGB: 'GBB',
  GBCB: 'GBB',
  HDFC: 'HDFC',
  HSBC: 'HSBC_IND',
  ICIC: 'ICICI',
  IBKL: 'IDBI',
  IOBA: 'IOB',
  VYSA: 'IVB',
  JAKA: 'JAKB',
  JSBP: 'JSB',
  KCCB: 'KCB',
  KJSB: 'KJSB',
  KARB: 'KARNATAKA',
  CHAS: 'JCB',
  KACE: 'KSAB',
  KSAC: 'KSAB',
  KSBK: 'KSAB',
  KVBL: 'KVN',
  KKBK: 'KMB',
  LAVB: 'LVB',
  MCBL: 'MAHANAGAR',
  MSCI: 'MSB',
  MSHM: 'MSB',
  MSHQ: 'MASHREQBANK',
  MSNU: 'MUB',
  MHCB: 'MIZUHO_IND',
  NTBL: 'NAINITAL',
  NICB: 'NIB',
  NICE: 'NIB',
  NKGS: 'NKGSB',
  NNSB: 'NNSB',
  OIBA: 'OIBS',
  ORBC: 'OBOC',
  PSPB: 'PJSB',
  PMCB: 'PAMB',
  PSIB: 'PASB',
  PUNB: 'PNB',
  RATN: 'RATNAKAR',
  RBIS: 'RBOI',
  SRCB: 'SARASWAT',
  SVCB: 'SVB',
  RBOS: 'RBOS',
  SHBK: 'SHINHAN_IND',
  SOGE: 'SG',
  SCBL: 'SCB',
  SBBJ: 'SBOBAJ',
  SBHY: 'SBOH',
  SIBL: 'SIB',
  STCB: 'SBOM',
  SBMY: 'SBOMYSORE',
  STBP: 'SBOP',
  SBTR: 'SBOT',
  SPCB: 'SPB',
  SURY: 'SPB',
  SYNB: 'SYNDICATE',
  TMBL: 'TMB',
  TJSB: 'TJSB',
  UCBA: 'UCO',
  UBIN: 'UNIOBOI',
  UTBI: 'UNITEDBOI',
  VIJB: 'VIJAYA',
  YESB: 'YES',
  TNSC: 'TSAB',
  // Not on Smilepayz list → OTHERS
  SBIN: 'OTHERS',
  IDFB: 'OTHERS',
  AIRP: 'OTHERS',
  IPOS: 'OTHERS',
  PYTM: 'OTHERS',
};

/**
 * Resolve Smilepayz payout paymentMethod from IFSC and/or an explicit method.
 * Prefer mapping from IFSC; if paymentMethod is already a known Smilepayz code, keep it.
 */
function resolvePayoutPaymentMethod({ ifscCode, paymentMethod } = {}) {
  const explicit = String(paymentMethod || '')
    .trim()
    .toUpperCase();
  if (explicit && SMILEPAYZ_PAYMENT_METHODS.has(explicit)) {
    return explicit;
  }

  const ifsc = String(ifscCode || explicit || '')
    .replace(/\s/g, '')
    .toUpperCase();
  const prefix = ifsc.slice(0, 4);
  if (prefix && IFSC_PREFIX_TO_METHOD[prefix]) {
    return IFSC_PREFIX_TO_METHOD[prefix];
  }

  return 'OTHERS';
}

module.exports = {
  SMILEPAYZ_PAYMENT_METHODS,
  IFSC_PREFIX_TO_METHOD,
  resolvePayoutPaymentMethod,
};
